; Granja Zenon - Cacao | Parcial 1
; DEV01 - Lote de cultivo 1 "Zenon Alto"  (Wokwi ESP32 #1)
;
;   pio run                 compila el firmware
;   wokwi-cli .             lanza la simulacion (o F1 -> "Wokwi: Start Simulator")

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    azure/Azure SDK for C@1.1.8

build_flags =
    -D MQTT_MAX_PACKET_SIZE=1024
    -D MQTT_KEEPALIVE=60
