[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    https://github.com/adafruit/Adafruit_SI1145_Library.git
    azure/Azure SDK for C@1.1.8

build_flags =
    -I include
    -D MQTT_MAX_PACKET_SIZE=1024
    -D MQTT_KEEPALIVE=60