; Granja Zenon - Cacao | Parcial 1
; DEV08 - Secado y fermentacion "Marinela"  (Wokwi ESP32 #2)
;
;   pio run                 compila el firmware
;   wokwi-cli .             lanza la simulacion

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    madhephaestus/ESP32Servo@^3.0.5
    azure/Azure SDK for C@1.1.8

build_flags =
    -D MQTT_MAX_PACKET_SIZE=1024
    -D MQTT_KEEPALIVE=60
